version: 2
jobs:
  posv2-contracts-e2e:
    docker:
      - image: aviramstern/aviram-orbs:ubuntu-go-node
    steps:
      - checkout
      - run: cd pos-v2 && ./test.sh
      - store_artifacts:
          path: pos-v2/_out
      - store_test_results:
          path: pos-v2/_reports

  posv2-testkit-consumer-e2e:
    docker:
      - image: aviramstern/aviram-orbs:ubuntu-go-node
    steps:
      - checkout
      - run: cd pos-v2-consumer && ./test.sh

workflows:
  version: 2
  build:
    jobs:
      - posv2-contracts-e2e
      - posv2-testkit-consumer-e2e
