version: "3"
services:
  gamma:
    image: orbs:unsanitry-gamma
    ports:
      - 8080:8080
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - 7545:7545
    command: -a 25 -m 'vanish junk genuine web seminar cook absurd royal ability series taste method identify elevator liquid' -i 5777 -p 7545
  voting:
    depends_on:
      - gamma
      - ganache
    image: orbs:voting
    command: tail -f /etc/hosts
    environment:
      GANACHE_URL: "http://ganache:7545"
      GAMMA_URL: "http://gamma:8080"
